### ISSUE TITLE
FYI: ReSharper 2012.2 test runner performance degradation when AutoFixture's AutoData for xunit is used

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#701]
You might see a noticable performance degradation when running tests that use AutoFixture `AutoDataAttribute` theory attribute for xunit using the ReSharper 2012.2.
This has been reported to R# team: [link](https://youtrack.jetbrains.com/issue/RSRP-460643). Issue is on R# side and is not related to the AutoFixture.

If you observe the issue too, please vote for the issue.

I've created this issue here in case somebody will look for the related information.

**Comment by laurencee** [comment]
Is this still a problem with 2016.3 release of ReSharper?

Can't say I've noticed a difference between using and not using autodata attributes.

**Comment by Zvirja** [comment]
Yes, it's still there.
It isn't reproducible on each solution. When I tried to create a steps to reproduce, I created a test solution and issue didn't happen there. However, my work project is still affected.

After I patched xunit to have stable names for each theory, issue started to appear during the first pass only - further re-run didn't suffer. Therefore, issue is definitely R# related.

**Comment by laurencee** [comment]
Just tested on one of my larger projects and xunit tests in general just take way longer to run in resharpers test runner than under vstest (test explorer in VS).

**Comment by erlis** [comment]
I was not able to leave a comment on that link you shared. I noticed also a bit delay while running my tests with Resharper runner. I'm using NUnit and AutoDataAttribute. If I put a breakpoint on the class I extend from AutoDataAttribute, I see a lot of hits, probably one per usage of this attribute on my code. 

When I started using the attribute I didn't noticed anything wrong but now that I have around 10K test is becoming evident that something is not right with the runner.

Can you share with me how can I write a message on that you track board?

Ohh wait I think they are marking this as fixed in version R# 2017.1 EAP5. I'll have to check that. 

Thanks anyway

**Comment by Zvirja** [comment]
I believe that you should register there to be able put your reply. 

The issue I reported is not about delay before the tests start to execute, it's rather about very slow execution speed. It wasn't fixed in the mentioned release. 
To spot whether you suffer from it you can compare execution time in VS and in Console. My result is about 1 minute in VS comparing to 5 secs in the Console. 

The delay looks like another issue. Test the latest xunit, console runner and latest R# EAP. If issue is present - report it on their tracker.

**Comment by zvirja** [comment]
Issue has been fixed in R# 2017.2 and is no longer reproducible 🎉🎉🌟
